[features]
seeds = false
skip-lint = false
[programs.localnet]
token_otc = "BuxnzeA7AXB77qpyg3d4Hk4RE7Qm7AXkfQ7Wh7dedLw4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noyan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
